### PR TITLE
Upgrade Rugged to 0.24.0

### LINKED ISSUE #15: Breaks gollum's revert_page
`gollum-lib`'s `Wiki#revert_page` [depends on](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/wiki.rb#L516) the underlying git adapter providing an `apply_patch` method. Unfortunately, due to `grit`'s unreliability, the tests for `Wiki#revert_page` were [commented out](https://github.com/gollum/gollum-lib/blob/master/test/test_page_revert.rb#L25-L51) a long time ago. So while `rugged_adapter` passes all of `gollum-lib`'s tests, it breaks gollum's "Revert Changes" functionality when you swap it in as the git adapter because `apply_patch` was [never actually implemented](https://github.com/gollum/rugged_adapter/blob/master/lib/rugged_adapter/git_layer_rugged.rb#L189-L191).

### PR DESCRIPTION
**Pull request by hiroponz**
This is a beta version but the maintainers mentioned that it's solid and they use it at GitHub.
And it needs the revert commit functionality from this version to resolve #15 .

### CODE REVIEW

**Comment by bartkamphorst** [comment]
Is there a timeline for the 0.24 non-beta release?

**Comment by hiroponz** [comment]
FYI. https://github.com/libgit2/libgit2/issues/3626

**Comment by bartkamphorst** [comment]
@hiroponz Version [0.24](https://rubygems.org/gems/rugged/versions/0.24.0) was just released. Care to adapt the PR?

**Comment by hiroponz** [comment]
@bartkamphorst I have upgraded the gem dependency.

**Comment by hiroponz** [comment]
The build failed, but the [last build](https://travis-ci.org/gollum/rugged_adapter/builds/98963365) have already failed.

**Comment by hiroponz** [comment]
@bartkamphorst The build passed, but it is temporary fix. Can you take a look?

**Comment by bartkamphorst** [comment]
The temporary spec fix seems fine to me. Have you tried running the gollum-lib specs using rugged `v. 0.24`?

**Comment by hiroponz** [comment]
1 error occurred at running the gollum-lib specs using rugged `v.0.24.0`, but also occurred on current rugged_adapter master(`v.0.23.3`).
The error message is like the following.

```
Error: test_push_and_pull(Pushing_and_pulling): NoMethodError: undefined method `save' for #<Rugged::Remote:0x007ff619eab818>
/Users/xxx/project/gollum/gollum-lib/vendor/bundle/ruby/2.2.0/bundler/gems/rugged_adapter-e3fd3664642b/lib/rugged_adapter/git_layer_rugged.rb:282:in `pull'
/Users/xxx/project/gollum/gollum-lib/test/test_hook.rb:91:in `block (2 levels) in <top (required)>'
```
@bartkamphorst Would you help me?

**Comment by hiroponz** [comment]
I found the following in the rugged [CHANGELOG](https://github.com/libgit2/rugged/blob/master/CHANGELOG.md).

```
Remote#clear_refspecs and Remote#save were removed without replacement.
```

**Comment by hiroponz** [comment]
FYI. https://github.com/libgit2/rugged/commit/559b09cc3e0659dcd0316050bdc44a8ec8e86aa1

**Comment by bartkamphorst** [comment]
Thanks @hiroponz . It looks like `save` is only called once, in the implementation of [pull](https://github.com/gollum/rugged_adapter/blob/master/lib/rugged_adapter/git_layer_rugged.rb#L282). Could you verify that removing that call does not break any functionality?

**Comment by hiroponz** [comment]
@bartkamphorst 
It seems that removing that call is OK, because it doesn't need to call `Remote#save` after `Remote#fetch`. Running the gollum-lib specs using rugged `v.0.24` passed after removing that call.

**Comment by bartkamphorst** [comment]
Thanks. @dometto Any other thoughts or comments before I merge?

**Comment by dometto** [comment]
Go ahead :) we should check whether we can improve on the adapter with the improvements to rugged though (maybe there is no need for some of the custom methods in the adapter anymore)

**Comment by bartkamphorst** [comment]
Thanks @hiroponz ! :+1:

**Comment by hiroponz** [comment]
You are welcome :)

**Comment by hiroponz** [comment]
@dometto Would you release the gem of new version? It needs for [this](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2999).

**Comment by dometto** [comment]
Released v0.4.2 just now.

**Comment by hiroponz** [comment]
Thanks!

**Pull request merged**
