### PR TITLE
Release 0.4.4

### PR DESCRIPTION
**Pull request by adamniedzielski**
I'm submitting this PR to make it slightly easier to release 0.4.4. /cc @dometto

### CODE REVIEW

**Comment by smcgivern** [comment]
@bartkamphorst I see you merged https://github.com/gollum/rugged_adapter/pull/26 - thanks! Do you know when a new version will be released?

**Comment by bartkamphorst** [comment]
Sorry, no clear timeline as of yet. Will discuss with @dometto.

**Comment by thomasjachmann** [comment]
@bartkamphorst @dometto Sorry to probably annoy you... but are there any news on that? I'm desperately awaiting a version of Gitlab with rugged version 0.25 (see #22/#26), so we need this fix to be released soon.

**Comment by adamniedzielski** [comment]
Thanks for releasing a new version! 🎊 🎺 🎈

**Pull request closed without merging**
