### PR TITLE
update rugged dependency for 0.25

### LINKED ISSUE #18: Update rugged to v. 0.24.0

### PR DESCRIPTION
**Pull request by glensc**
fixes using rugged 0.25

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8538#note_21302761

please release new version as well when merged

also closes #18 once merged (altho it could be already closed as #17 is merged)

### CODE REVIEW

**Comment by stanhu** [comment]
@glensc Thanks! 

We'll need this for GitLab.

**Comment by bartkamphorst** [comment]
Have you tested gollum with this version of rugged by any chance?

**Comment by glensc** [comment]
just tested only basic things i could think of in gitlab wiki:
- create page
- edit page
- page history
- view specific page in history

**Comment by thomasjachmann** [comment]
@bartkamphorst Could you specify what should be tested further in order to get the new rugged version merged in? Basic functionality was tested manually by @glensc and the `adapter_specs` have been run successfully, shouldn't this cover most of it?

Maybe you're more comfortable with a more backwards-compatible dependency change to `'~> 0.24'` that would loosen the dependencies a bit? This way, existing users could still keep using rugged v0.24 while anyone could choose to update rugged to any 0.x version at will. If unexpected problems arise with v0.25, one could also pin the rugged version to v0.24 in the client application's `Gemfile`. Since both gollum-rugged_adapter and rugged are in their 0.x prefinal state, a user cannot be secure from incompatible changes even in minor/bugfix version updates anyway. Not that I had any bad experiences with any of both teams, that's just how I generally approach using prefinal gems.

I'd also just like to have rugged in the current version in GitLab since v.24 contains a bug that makes GitLab unusable for my project. :)

**Comment by dometto** [comment]
Sorry for the slow response time, @bartkamphorst and I have both been very busy. I think what @bartkamphorst meant was to run the gollum and gollum-lib tests while using this version of the rugged_adapter. So:

* Add your local version of the rugged adapter to the gollum-lib (and gollum) Gemfile:
    * `gem "gollum-rugged_adapter", :path => '/path/to/rugged_adapter'`
    * `bundle install`
    * `bundle exec rake GIT_ADAPTER=rugged`

At the moment the adapter specs are in practice too minimal: probably we would need to move some of the tests from the gollum-lib suite to the adapter specs -- or rather, reimplement them in rspec (which also explains why we haven't done so yet).

**Comment by rymai** [comment]
For what it's worth, following are the test suites of `gollum` and `gollum-lib` with Rugged `0.25.1.1`. The `gollum` test suite is failing.

### gollum-lib

#### Gemfile.lock

```
› cat Gemfile.lock | grep rugged
  remote: git://github.com/glensc/rugged_adapter.git
    gollum-rugged_adapter (0.4.3)
      rugged (~> 0.25.0)
    rugged (0.25.1.1)
  gollum-rugged_adapter!
```

#### Tests (OK)

```
› bundle exec rake GIT_ADAPTER=rugged
/Users/remy/.rubies/ruby-2.3.3/bin/ruby -I"lib:lib:test:." -I"/Users/remy/.rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib" "/Users/remy/.rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/**/test_*.rb" 
Loaded suite /Users/remy/.rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/rake_test_loader
Started
...............................................................................................................................
...............................................................................................................................
....................

Finished in 6.869705 seconds.
-------------------------------------------------------------------------------------------------------------------------------
274 tests, 635 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------------------------------------------------------
39.89 tests/s, 92.43 assertions/s
```

### gollum

#### Gemfile.lock

```
› cat Gemfile.lock | grep rugged
  remote: git://github.com/glensc/rugged_adapter.git
    gollum-rugged_adapter (0.4.3)
      rugged (~> 0.25.0)
    rugged (0.25.1.1)
  gollum-rugged_adapter!
```

#### Tests (failures)

```
› bundle exec rake GIT_ADAPTER=rugged           
/Users/remy/.rubies/ruby-2.3.3/bin/ruby -I"lib:lib:test:." -I"/Users/remy/.gem/ruby/2.3.3/gems/rake-10.5.0/lib" "/Users/remy/.gem/ruby/2.3.3/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/**/test_*.rb" 
Loaded suite /Users/remy/.gem/ruby/2.3.3/gems/rake-10.5.0/lib/rake/rake_test_loader
Started
....................................F
===============================================================================================================================
Failure: test_urls_transform_unicode(Frontend)
/Users/remy/Desktop/gollum/test/test_app.rb:38:in `block (2 levels) in <top (required)>'
<"m-plus-F"> expected but was
<"μ†ℱ">
===============================================================================================================================
....E
===============================================================================================================================
Error: test_transliteration(Frontend_Unicode_support): Rugged::InvalidError: Failed to parse signature - Signature cannot have an empty name or email
/Users/remy/.gem/ruby/2.3.3/bundler/gems/rugged_adapter-954c6a313a0b/lib/rugged_adapter/git_layer_rugged.rb:461:in `create'
/Users/remy/.gem/ruby/2.3.3/bundler/gems/rugged_adapter-954c6a313a0b/lib/rugged_adapter/git_layer_rugged.rb:461:in `commit'
/Users/remy/.gem/ruby/2.3.3/gems/gollum-lib-4.2.2/lib/gollum-lib/committer.rb:170:in `commit'
/Users/remy/.gem/ruby/2.3.3/gems/gollum-lib-4.2.2/lib/gollum-lib/wiki.rb:357:in `write_page'
/Users/remy/Desktop/gollum/test/test_unicode.rb:94:in `block (2 levels) in <top (required)>'
===============================================================================================================================
.............................

Finished in 3.806523 seconds.
-------------------------------------------------------------------------------------------------------------------------------
71 tests, 199 assertions, 1 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
97.1831% passed
-------------------------------------------------------------------------------------------------------------------------------
18.65 tests/s, 52.28 assertions/s
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test:." -I"/Users/remy/.gem/ruby/2.3.3/gems/rake-10.5.0/lib" "/Users/remy/.gem/ruby/2.3.3/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/**/test_*.rb" ]
/Users/remy/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/cli/exec.rb:74:in `load'
/Users/remy/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/remy/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/cli/exec.rb:27:in `run'
/Users/remy/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/cli.rb:335:in `exec'
/Users/remy/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/remy/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/remy/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/remy/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/cli.rb:20:in `dispatch'
/Users/remy/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/remy/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/cli.rb:11:in `start'
/Users/remy/.gem/ruby/2.3.3/gems/bundler-1.14.2/exe/bundle:32:in `block in <top (required)>'
/Users/remy/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/Users/remy/.gem/ruby/2.3.3/gems/bundler-1.14.2/exe/bundle:24:in `<top (required)>'
/Users/remy/.gem/ruby/2.3.3/bin/bundle:22:in `load'
/Users/remy/.gem/ruby/2.3.3/bin/bundle:22:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by adamniedzielski** [comment]
@rymai and all interested: these two failures are not related to upgrading the version of `rugged`. They also happen when running `gollum` test suite with `rugged_adapter` 0.4.3 - see https://github.com/gollum/gollum/issues/1187.

**Comment by dometto** [comment]
Thanks for reporting, @rymai  and @adamniedzielski. Given that we see no new test failures, I'll merge this!

**Comment by adamniedzielski** [comment]
@dometto Thank you so much for merging this! Can you also release a new gem version that includes this change?

**Pull request merged**
