### PR TITLE
Add rev_parse(spec)

### PR DESCRIPTION
**Pull request by heavywatal**
This will followed by another PR in gollum-lib, which provides an efficient way to get SHA1 of a given path:

```
module Gollum
  class Wiki
    def rev_parse(path, rev = @ref)
      spec = "#{rev}:#{path}"
      @repo.rev_parse(spec)
    end
  end
end
```

### CODE REVIEW

**Comment by heavywatal** [comment]
Oops, it returns a rugged Object, which I guess is not appropriate to be returned from an adapter function.

**Comment by dometto** [comment]
> Oops, it returns a rugged Object, which I guess is not appropriate to be returned from an adapter function.

That's right, because we also have the [rjgit adapter](https://github.com/gollum/rjgit_adapter). Can you describe the functionality you want to implement? It should return a SHA, I think? What is `spec` here, exactly?

**Comment by heavywatal** [comment]
My first motivation was to improve `Gollum::Wiki.page()` and `Gollum::File.find()` in gollum-lib, and I found `git rev-parse` works simply (and more efficiently, I guess). E.g.,

- `git rev-parse master:Gemfile` returns the blob SHA1
- `git rev-parse master:lib/` returns the tree SHA1
- `git rev-parse master` returns the commit SHA1

And libgit2/rugged `rev_parse()` returns a more convenient object derived from Object class: Blob, Tree, or Commit. This PR was adding just an accessor of it (which turned out not appropriate attitude here).

Unfortunately, rjgit and jgit seem not provide `rev-parse` function, and It seems very difficult for me to take of all the adapters and specs. Maybe I should keep it in my branch and `config.rb`...?

**Comment by dometto** [comment]
> My first motivation was to improve Gollum::Wiki.page() and Gollum::File.find() in gollum-lib, and I found git rev-parse works simply (and more efficiently, I guess).

That's a nice idea! Is this then not related to https://github.com/gollum/gollum/pull/1543?

I see a problem with using `rev_parse` as a method for page lookup: gollum can also resolve `Page`, not just `Page.md`. That requires going through the repo looking for pages whose basename (without extension) is `Page`. `rev_parse` could not do that; it would only support looking up `Page.md`. So yes, if that's what you're doing for your personal wiki, it's probably best to keep that local. Thanks again for contributing, and let us know if we can help with anything!

**Comment by heavywatal** [comment]
Thank you for the comments. I agree that the current `rev_parse()` does not immediately replace the existing lookup functions. But it provides very concise ways to travers trees and blobs from an arbitrary path, e.g., listing only files under the `@page_file_dir` or in the same directory as the current page. I hope it will be adopted to jgit and the adapter spec in the future.

> Is this then not related to gollum/gollum#1543?

Yes and no. The current implementation uses `rev_parse()`, but it may not be impossible to rewrite it with other existing functions. I will give it a try.

**Comment by dometto** [comment]
I also like the efficiency. One approach could be to refactor the `find` method in gollum-lib's `File` or `Page` class in such a way that, when the requested file has a valid file extension, we use a different adapter method. For rugged, that different method could use `rev_spec` in the background. For RJGit, as long as/if JGit doesn't have an equivalent, it could just use the regular method.

**Pull request closed without merging**
